import { useEffect, useState } from "react";
import { CheckCircle2, Loader2, Zap } from "lucide-react";
import { useCompany } from "../context/CompanyContext";

// Boot splash played after a profile is switched. When the profile was just
// generated by /api/companies/seed we have real provenance (`_meta`) and show
// actual numbers — duration, token counts, vocab size — so the rep (and the
// user inspecting the demo) can verify the LLM call really happened. For
// library switches there's no meta, and we fall back to the simpler animation.

const STEPS = [
  { ms: 200,  label: "Pulling homepage + recent filings" },
  { ms: 600,  label: "Resolving competitor set + peer benchmarks" },
  { ms: 1000, label: "Mapping operational geography + named distribution centres" },
  { ms: 1500, label: "Threading recent news into anomaly inbox" },
  { ms: 2000, label: "Seeding all 13 intelligence layers" },
  { ms: 2500, label: "Computing scenario war-room baselines" },
];

function formatDuration(ms: number): string {
  return ms < 1000 ? `${ms}ms` : `${(ms / 1000).toFixed(1)}s`;
}
function formatBytes(n: number): string {
  return n < 1024 ? `${n} B` : `${(n / 1024).toFixed(1)} KB`;
}
function formatInt(n: number): string {
  return n.toLocaleString();
}
// White-label the underlying model identifier as a DifferentDay AI engine tier
// so the receipt reads as our product, not the raw upstream provider name.
function brandModel(_raw: string): string {
  return "DifferentDay AI · core";
}

export default function CompanyBootSplash() {
  const { bootSplash } = useCompany();
  const [tick, setTick] = useState(0);

  useEffect(() => {
    if (!bootSplash?.open) return undefined;
    setTick(0);
    const timers = STEPS.map((s, i) => setTimeout(() => setTick(i + 1), s.ms));
    return () => { timers.forEach(clearTimeout); };
  }, [bootSplash?.open, bootSplash?.profileName]);

  if (!bootSplash?.open) return null;

  const meta = bootSplash.meta;

  return (
    <div role="status" aria-live="polite" aria-label="Seeding company intelligence"
         className="fixed inset-0 z-[70] flex items-center justify-center px-6"
         style={{ background: "rgba(15,26,51,0.92)" }}>
      <div className="w-[620px] max-w-full">
        <div className="text-center mb-6">
          <div className="eyebrow text-[var(--gold-light)] mb-2">Different Day · Elevated Intelligence</div>
          <h1 className="font-serif font-semibold text-[40px] leading-[1.05] text-[var(--cream)] mb-2">
            Seeding the framework for
          </h1>
          <div className="font-serif font-bold text-[44px] leading-tight" style={{ color: "var(--gold-light)" }}>
            {bootSplash.profileName}
          </div>
        </div>

        <ul className="space-y-2.5">
          {STEPS.map((s, i) => {
            const done = i < tick;
            const active = i === tick;
            return (
              <li key={i} className="flex items-center gap-3 px-4 py-2.5 rounded-sm transition-opacity"
                  style={{
                    background: done ? "rgba(212,175,55,0.10)" : active ? "rgba(212,175,55,0.06)" : "rgba(255,255,255,0.02)",
                    opacity: done || active ? 1 : 0.45,
                    border: done ? "1px solid rgba(212,175,55,0.35)" : "1px solid rgba(255,255,255,0.08)",
                  }}>
                <span className="shrink-0">
                  {done
                    ? <CheckCircle2 size={16} strokeWidth={1.8} style={{ color: "var(--gold-light)" }} />
                    : active
                      ? <Loader2 size={16} strokeWidth={1.8} className="animate-spin" style={{ color: "var(--gold-light)" }} />
                      : <span className="block h-3 w-3 rounded-full" style={{ background: "rgba(255,255,255,0.18)", marginLeft: 2 }} />}
                </span>
                <span className={"font-sans text-[13px] " + (done ? "text-[var(--cream)]" : "text-[var(--cream)]/80")}>
                  {s.label}
                </span>
              </li>
            );
          })}
        </ul>

        {meta && (
          <div className="mt-5 p-4 rounded-sm"
               style={{ background: "rgba(212,175,55,0.06)", border: "1px solid rgba(212,175,55,0.30)" }}>
            <div className="flex items-center gap-1.5 mb-2.5">
              <Zap size={12} strokeWidth={2} style={{ color: "var(--gold-light)" }} />
              <span className="font-sans text-[10px] uppercase tracking-wider text-[var(--gold-light)]">
                Live receipt · just generated
              </span>
            </div>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-x-4 gap-y-2.5">
              <Stat label="Engine"         value={brandModel(meta.model)} mono />
              <Stat label="Round-trip"     value={formatDuration(meta.durationMs)} mono />
              <Stat label="Tokens in/out"  value={
                meta.inputTokens !== null && meta.outputTokens !== null
                  ? `${formatInt(meta.inputTokens)} → ${formatInt(meta.outputTokens)}`
                  : "—"
              } mono />
              <Stat label="Payload"        value={formatBytes(meta.bytesReturned)} mono />
              <Stat label="Vocab tokens"   value={formatInt(meta.vocabCount)} mono />
              <Stat label="Headline metrics" value={formatInt(meta.headlinesCount)} mono />
            </div>
          </div>
        )}

        <div className="text-center mt-5 font-serif italic text-[12px] text-[var(--cream)]/55">
          {meta
            ? "Receipt above is real DifferentDay AI provenance, captured from this seed request."
            : "Synthetic seed data · the sales rep should review before the meeting"}
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div>
      <div className="font-sans text-[9px] uppercase tracking-wider text-[var(--cream)]/55 mb-0.5">{label}</div>
      <div className={"text-[13px] text-[var(--cream)] truncate " + (mono ? "font-mono" : "font-sans")}>{value}</div>
    </div>
  );
}
