import { useEffect, useState } from "react";
import { X, Printer, Sparkles, Building2, Users2, LineChart, Lightbulb, RefreshCw } from "lucide-react";
import { useCompany } from "../context/CompanyContext";

interface Brief {
  company:  { snapshot: string; history: string; businessModel: string; differentiators: string[] };
  leaders:  Array<{ name: string; role: string; background: string }>;
  financials: {
    scale: string; trajectory: string; capitalStructure: string;
    kpis: Array<{ label: string; value: string; note?: string }>;
  };
  aiOpportunities: Array<{
    title: string; where: string; problem: string; solution: string;
    impact: string; horizon: "Now" | "6 months" | "12+ months";
  }>;
  narrative: string;
  generatedAt: string;
}

const CACHE_PREFIX = "differentday.intelligenceBrief.v1.";

function loadCached(profileId: string): Brief | null {
  try {
    const raw = window.localStorage.getItem(CACHE_PREFIX + profileId);
    return raw ? JSON.parse(raw) as Brief : null;
  } catch { return null; }
}

function saveCached(profileId: string, brief: Brief): void {
  try { window.localStorage.setItem(CACHE_PREFIX + profileId, JSON.stringify(brief)); } catch { /* ignore */ }
}

export default function IntelligenceBrief({ onClose }: { onClose: () => void }) {
  const { profile } = useCompany();
  const [brief, setBrief] = useState<Brief | null>(() => loadCached(profile.id));
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Rehydrate cache and clear stale state whenever the active profile
  // changes while the modal is open — otherwise the brief from the
  // previous profile would linger and the auto-generate effect would
  // skip the new one because `brief` is still truthy.
  useEffect(() => {
    setBrief(loadCached(profile.id));
    setError(null);
  }, [profile.id]);

  async function generate(force = false): Promise<void> {
    if (!force && brief) return;
    setLoading(true);
    setError(null);
    try {
      const url = `${import.meta.env.BASE_URL}api/intelligence/brief${force ? "?refresh=1" : ""}`;
      const resp = await fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          name:        profile.name,
          url:         profile.url,
          sector:      profile.sector,
          hqCity:      profile.hqCity,
          hqState:     profile.hqState,
          revenueBand: profile.revenueBand,
          ownership:   profile.ownership,
          founded:     profile.founded,
          tagline:     profile.tagline,
        }),
      });
      const data = await resp.json() as Brief | { error?: string };
      if (!resp.ok) {
        const msg = (data as { error?: string }).error ?? `Request failed (HTTP ${resp.status})`;
        throw new Error(msg);
      }
      const b = data as Brief;
      setBrief(b);
      saveCached(profile.id, b);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Brief generation failed.");
    } finally {
      setLoading(false);
    }
  }

  // Auto-generate on first open if no cache for this profile
  useEffect(() => {
    if (!brief && !loading && !error) void generate(false);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [profile.id]);

  // ESC closes
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => { if (e.key === "Escape") onClose(); };
    window.addEventListener("keydown", onKey);
    return () => window.removeEventListener("keydown", onKey);
  }, [onClose]);

  return (
    <div className="fixed inset-0 z-50 flex flex-col" style={{ background: "rgba(15,26,51,0.55)" }} onClick={onClose}>
      {/* Toolbar */}
      <div className="h-[44px] shrink-0 flex items-center justify-between px-6 border-b border-[var(--navy-deep)]"
           style={{ background: "var(--navy)", color: "var(--cream)" }}
           onClick={(e) => e.stopPropagation()}>
        <div className="flex items-center gap-3">
          <Sparkles size={14} className="text-[var(--gold-light)]" />
          <span className="eyebrow text-[var(--gold-light)]">Company intelligence · {profile.name}</span>
          <span className="font-sans text-[12px] opacity-70">Generated by DifferentDay AI · CEO read</span>
        </div>
        <div className="flex items-center gap-3">
          <button onClick={() => void generate(true)} disabled={loading}
                  className="inline-flex items-center gap-1.5 font-sans text-[12px] opacity-80 hover:opacity-100 disabled:opacity-40">
            <RefreshCw size={13} className={loading ? "animate-spin" : ""} /> Regenerate
          </button>
          <button onClick={() => window.print()}
                  className="inline-flex items-center gap-1.5 font-sans text-[12px] opacity-80 hover:opacity-100">
            <Printer size={13} /> Print
          </button>
          <button onClick={onClose} aria-label="Close" className="opacity-80 hover:opacity-100">
            <X size={18} />
          </button>
        </div>
      </div>

      {/* Scrollable body */}
      <div className="flex-1 overflow-y-auto" onClick={(e) => e.stopPropagation()}>
        <div className="max-w-[920px] mx-auto py-10 px-10" style={{ background: "var(--cream)", minHeight: "100%" }}>
          {/* Masthead */}
          <div className="border-b-2 border-[var(--navy)] pb-6 mb-8">
            <div className="eyebrow text-[var(--coral)] mb-2">DIFFERENT DAY · COMPANY INTELLIGENCE</div>
            <div className="flex items-baseline gap-3">
              {profile.logoEmoji && <span style={{ fontSize: 36 }}>{profile.logoEmoji}</span>}
              <h1 className="font-serif text-[44px] leading-tight font-semibold text-[var(--navy)]">{profile.name}</h1>
            </div>
            <div className="font-sans italic text-[13px] text-[var(--slate)] mt-2">
              {profile.sector} · {profile.hqCity}{profile.hqState ? `, ${profile.hqState}` : ""} · {profile.revenueBand}
              {profile.founded ? ` · Founded ${profile.founded}` : ""}
            </div>
            {profile.tagline && (
              <div className="font-sans text-[13px] text-[var(--slate)] mt-1">{profile.tagline}</div>
            )}
          </div>

          {/* Loading / error states */}
          {loading && !brief && <LoadingSkeleton />}
          {error && !brief && (
            <div className="card card-accent-coral">
              <div className="eyebrow text-[var(--coral)] mb-2">BRIEFING FAILED</div>
              <div className="font-sans text-[13px] text-[var(--ink)]">{error}</div>
              <button onClick={() => void generate(true)}
                      className="mt-4 inline-flex items-center gap-1.5 font-sans font-semibold text-[12px] text-[var(--navy)] underline">
                <RefreshCw size={13} /> Try again
              </button>
            </div>
          )}

          {brief && (
            <>
              {/* Integrated narrative pull-quote */}
              <div className="mb-10 pl-6 border-l-4 border-[var(--coral)]">
                <div className="eyebrow text-[var(--coral)] mb-2">THE THESIS</div>
                <p className="font-serif italic text-[18px] leading-relaxed text-[var(--ink)]">
                  {brief.narrative}
                </p>
              </div>

              {/* Section: Company */}
              <Section icon={Building2} title="Company" accent="var(--navy)">
                <Para>{brief.company.snapshot}</Para>
                <SubHeader>History</SubHeader>
                <Para>{brief.company.history}</Para>
                <SubHeader>Business model</SubHeader>
                <Para>{brief.company.businessModel}</Para>
                {brief.company.differentiators.length > 0 && (
                  <>
                    <SubHeader>Differentiators</SubHeader>
                    <ul className="space-y-1.5 mt-2">
                      {brief.company.differentiators.map((d, i) => (
                        <li key={i} className="font-sans text-[14px] text-[var(--ink)] leading-snug flex gap-2">
                          <span className="text-[var(--coral)] font-bold">·</span>
                          <span>{d}</span>
                        </li>
                      ))}
                    </ul>
                  </>
                )}
              </Section>

              {/* Section: Leaders */}
              <Section icon={Users2} title="Leaders" accent="var(--gold)">
                <div className="grid grid-cols-2 gap-x-6 gap-y-5">
                  {brief.leaders.map((l, i) => (
                    <div key={i} className="border-l-2 border-[var(--cream-dark)] pl-4">
                      <div className="font-serif font-semibold text-[16px] text-[var(--navy)] leading-tight">{l.name}</div>
                      <div className="font-sans text-[12px] text-[var(--coral)] uppercase tracking-wide font-bold mt-0.5">{l.role}</div>
                      <div className="font-sans text-[13px] text-[var(--ink)] mt-1.5 leading-snug">{l.background}</div>
                    </div>
                  ))}
                </div>
              </Section>

              {/* Section: Financials */}
              <Section icon={LineChart} title="Financials" accent="var(--teal)">
                {brief.financials.kpis.length > 0 && (
                  <div className="grid grid-cols-4 gap-3 mb-5">
                    {brief.financials.kpis.map((k, i) => (
                      <div key={i} className="card !p-3">
                        <div className="eyebrow text-[var(--slate-light)] text-[10px]">{k.label}</div>
                        <div className="font-serif font-semibold text-[22px] text-[var(--navy)] tabular-nums leading-tight mt-1">{k.value}</div>
                        {k.note && <div className="font-sans text-[10px] text-[var(--slate)] mt-0.5 tabular-nums">{k.note}</div>}
                      </div>
                    ))}
                  </div>
                )}
                <SubHeader>Scale</SubHeader>
                <Para>{brief.financials.scale}</Para>
                <SubHeader>Trajectory</SubHeader>
                <Para>{brief.financials.trajectory}</Para>
                <SubHeader>Capital structure</SubHeader>
                <Para>{brief.financials.capitalStructure}</Para>
              </Section>

              {/* Section: AI Opportunities */}
              <Section icon={Lightbulb} title="Where AI moves the needle" accent="var(--coral)">
                <div className="space-y-5">
                  {brief.aiOpportunities.map((o, i) => (
                    <div key={i} className="card card-accent-coral">
                      <div className="flex items-start justify-between gap-3 mb-2">
                        <div>
                          <div className="font-serif font-semibold text-[18px] text-[var(--navy)] leading-tight">{o.title}</div>
                          <div className="font-sans text-[11px] text-[var(--slate)] uppercase tracking-wide mt-1">{o.where}</div>
                        </div>
                        <span className={`pill shrink-0 ${o.horizon === "Now" ? "pill-coral" : o.horizon === "6 months" ? "pill-amber" : "pill-teal"}`}>
                          {o.horizon}
                        </span>
                      </div>
                      <SubHeader compact>The problem</SubHeader>
                      <Para small>{o.problem}</Para>
                      <SubHeader compact>The AI play</SubHeader>
                      <Para small>{o.solution}</Para>
                      <div className="mt-3 pt-3 border-t border-[var(--cream-dark)] flex items-baseline gap-2">
                        <span className="eyebrow text-[var(--teal)]">Impact</span>
                        <span className="font-sans font-semibold text-[13px] text-[var(--ink)]">{o.impact}</span>
                      </div>
                    </div>
                  ))}
                </div>
              </Section>

              <div className="mt-10 pt-4 border-t border-[var(--cream-dark)] font-sans italic text-[11px] text-[var(--slate-light)]">
                Generated by DifferentDay AI · {new Date(brief.generatedAt).toLocaleString()} · Briefing is illustrative and intended for internal sales preparation only.
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function Section({ icon: Icon, title, accent, children }: {
  icon: React.ComponentType<{ size?: number; className?: string }>;
  title: string; accent: string; children: React.ReactNode;
}) {
  return (
    <section className="mb-10">
      <div className="flex items-center gap-2 mb-4 pb-2 border-b border-[var(--cream-dark)]">
        <Icon size={18} className="shrink-0" />
        <h2 className="font-serif font-semibold text-[24px] text-[var(--navy)]" style={{ borderLeft: `4px solid ${accent}`, paddingLeft: 12 }}>{title}</h2>
      </div>
      {children}
    </section>
  );
}
function SubHeader({ children, compact }: { children: React.ReactNode; compact?: boolean }) {
  return (
    <div className={`eyebrow text-[var(--slate-light)] ${compact ? "mt-2" : "mt-4"} mb-1`}>{children}</div>
  );
}
function Para({ children, small }: { children: React.ReactNode; small?: boolean }) {
  return (
    <p className={`font-sans ${small ? "text-[13px]" : "text-[14px]"} text-[var(--ink)] leading-relaxed`}>{children}</p>
  );
}

function LoadingSkeleton() {
  return (
    <div className="space-y-8 animate-pulse">
      <div>
        <div className="h-3 w-32 bg-[var(--cream-dark)] rounded mb-2" />
        <div className="h-6 bg-[var(--cream-dark)] rounded mb-1.5 w-[92%]" />
        <div className="h-6 bg-[var(--cream-dark)] rounded mb-1.5 w-[88%]" />
        <div className="h-6 bg-[var(--cream-dark)] rounded w-[70%]" />
      </div>
      {[1, 2, 3, 4].map(i => (
        <div key={i}>
          <div className="h-5 w-40 bg-[var(--cream-dark)] rounded mb-3" />
          <div className="h-3 bg-[var(--cream-dark)] rounded mb-2 w-full" />
          <div className="h-3 bg-[var(--cream-dark)] rounded mb-2 w-[94%]" />
          <div className="h-3 bg-[var(--cream-dark)] rounded mb-2 w-[88%]" />
          <div className="h-3 bg-[var(--cream-dark)] rounded w-[75%]" />
        </div>
      ))}
      <div className="font-sans italic text-[12px] text-[var(--slate)] text-center pt-2">
        DifferentDay AI is researching the company and drafting the brief — typically 10-20 seconds…
      </div>
    </div>
  );
}
