// Narrator panel content. Per-tenant narrator copy is generated by the
// pipeline as the `narrator` artifact and surfaced via CompanyContext.
// This module exports the type contracts only.

export interface CrossInsight {
  icon: "link" | "alert" | "trend";
  title: string;
  body: string;
  targetLayer: string;
  targetField?: string;
}
export interface NextStep { title: string; targetLayer: string; }
export interface NarratorContent {
  summary: string;
  cross: CrossInsight[];
  next: NextStep[];
}

export const NARRATOR: Record<string, NarratorContent> = {};
