// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portal-dossier/Dossier.tsx": () => import("../components/mockups/portal-dossier/Dossier.tsx"),
  "./components/mockups/portal-editorial/Editorial.tsx": () => import("../components/mockups/portal-editorial/Editorial.tsx"),
  "./components/mockups/portal-warroom/WarRoom.tsx": () => import("../components/mockups/portal-warroom/WarRoom.tsx"),
  "./components/mockups/portal-terminal/Terminal.tsx": () => import("../components/mockups/portal-terminal/Terminal.tsx")
};
