// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portal-dossier/Customer.tsx": () => import("../components/mockups/portal-dossier/Customer.tsx"),
  "./components/mockups/portal-dossier/Dossier.tsx": () => import("../components/mockups/portal-dossier/Dossier.tsx"),
  "./components/mockups/portal-dossier/Finance.tsx": () => import("../components/mockups/portal-dossier/Finance.tsx"),
  "./components/mockups/portal-dossier/Pricing.tsx": () => import("../components/mockups/portal-dossier/Pricing.tsx"),
  "./components/mockups/portal-terminal/Terminal.tsx": () => import("../components/mockups/portal-terminal/Terminal.tsx"),
  "./components/mockups/portal-editorial/Editorial.tsx": () => import("../components/mockups/portal-editorial/Editorial.tsx"),
  "./components/mockups/portal-warroom/Demand.tsx": () => import("../components/mockups/portal-warroom/Demand.tsx"),
  "./components/mockups/portal-warroom/Marketing.tsx": () => import("../components/mockups/portal-warroom/Marketing.tsx"),
  "./components/mockups/portal-warroom/Supply.tsx": () => import("../components/mockups/portal-warroom/Supply.tsx"),
  "./components/mockups/portal-warroom/WarRoom.tsx": () => import("../components/mockups/portal-warroom/WarRoom.tsx")
};
