import { jsonb, pgTable, text, timestamp, unique, uuid } from "drizzle-orm/pg-core";
import { tenantsTable } from "./tenants";

export const tenantLayersTable = pgTable(
  "tenant_layers",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    tenantId: uuid("tenant_id")
      .notNull()
      .references(() => tenantsTable.id, { onDelete: "cascade" }),
    layerKey: text("layer_key").notNull(),
    content: jsonb("content").notNull().$type<Record<string, unknown>>(),
    // hero_panel is generated by an extra Phase 2 sub-stage AFTER narrate+score.
    // It is nullable because: (a) older tenants seeded before this column
    // existed will have NULL until backfilled via POST /tenants/:id/hero/backfill,
    // and (b) the hero sub-stage is allowed to fail without degrading the
    // layer (the frontend gracefully falls back to the metric-only snapshot).
    heroPanel: jsonb("hero_panel").$type<Record<string, unknown>>(),
    // peer_benchmark is generated by a Phase 2 sub-stage (Peers) that runs
    // after Hero. Same rationale as heroPanel for nullability: backfill
    // path for older tenants + the stage is allowed to fail without
    // degrading the layer (the frontend just skips the peer card).
    peerBenchmark: jsonb("peer_benchmark").$type<Record<string, unknown>>(),
    // supplement_blocks is generated by Phase 2 sub-stage 8 (Supplements).
    // Same nullability rationale as the other panel columns. Stored as
    // `{ blocks: SupplementBlock[] }` — see phase2-schemas for the
    // discriminated union (leaderboard, matrix, timeline, callout).
    supplementBlocks: jsonb("supplement_blocks").$type<Record<string, unknown>>(),
    verifiedClaims: jsonb("verified_claims")
      .notNull()
      .$type<unknown[]>()
      .default([]),
    modelledClaims: jsonb("modelled_claims")
      .notNull()
      .$type<unknown[]>()
      .default([]),
    generatedAt: timestamp("generated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    generatorModel: text("generator_model").notNull(),
  },
  (t) => [unique("tenant_layers_tenant_id_layer_key_unique").on(t.tenantId, t.layerKey)],
);

export type TenantLayer = typeof tenantLayersTable.$inferSelect;
export type InsertTenantLayer = typeof tenantLayersTable.$inferInsert;
